
:- module(ingredients_kb, [
    nutriton/5
]).

nutriton('BANANA','NATURAL',1,calories,95).
nutriton('BANANA','NATURAL',1,carbohydrates,21.8).
nutriton('BANANA','NATURAL',1,fats,0.2).
nutriton('BANANA','NATURAL',1,proteins,1.5).
nutriton('GLAIR','NATURAL',1,calories,44).
nutriton('GLAIR','NATURAL',1,carbohydrates,0.0).
nutriton('GLAIR','NATURAL',1,fats,0.0).
nutriton('GLAIR','NATURAL',1,proteins,11.1).
nutriton('EGG','NATURAL',1,calories,157).
nutriton('EGG','NATURAL',1,carbohydrates,0.7).
nutriton('EGG','NATURAL',1,fats,10.9).
nutriton('EGG','NATURAL',1,proteins,12.7).
nutriton('FLOUR','TABLESPOON',1,calories,72).
nutriton('FLOUR','TABLESPOON',1,carbohydrates,16.0).
nutriton('FLOUR','TABLESPOON',1,fats,0.1).
nutriton('FLOUR','TABLESPOON',1,proteins,1.5).
nutriton('OAT','GRAM',100,calories,342).
nutriton('OAT','GRAM',100,carbohydrates,59.5).
nutriton('OAT','GRAM',100,fats,6.1).
nutriton('OAT','GRAM',100,proteins,12.3).
nutriton('PEACH','NATURAL',1,calories,46).
nutriton('PEACH','NATURAL',1,carbohydrates,11.3).
nutriton('PEACH','NATURAL',1,fats,0.1).
nutriton('PEACH','NATURAL',1,proteins,0.9).
nutriton('COTTAGE_CHEESE','GRAM',100,calories,121).
nutriton('COTTAGE_CHEESE','GRAM',100,carbohydrates,1.8).
nutriton('COTTAGE_CHEESE','GRAM',100,fats,5.0).
nutriton('COTTAGE_CHEESE','GRAM',100,proteins,17.2).
nutriton('MILK','MILLILITER',100,calories,59).
nutriton('MILK','MILLILITER',100,carbohydrates,4.7).
nutriton('MILK','MILLILITER',100,fats,3.2).
nutriton('MILK','MILLILITER',100,proteins,2.9).
nutriton('DARK_CHOCOLATE','GRAM',100,calories,539).
nutriton('DARK_CHOCOLATE','GRAM',100,carbohydrates,48.2).
nutriton('DARK_CHOCOLATE','GRAM',100,fats,35.4).
nutriton('DARK_CHOCOLATE','GRAM',100,proteins,6.2).
